/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controller;
import Database.*;
import sign_up.SignUpProcess;

/**
 *
 * @author kn
 */
public class Window extends javax.swing.JFrame {

    private SignUpProcess sign_up_prod = new SignUpProcess();
    private Users user = new Users();
    private Icons icon = new Icons();
    private Highest_result hi_re = new Highest_result();
    private Checkpoint check = new Checkpoint();
    
    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel_sign_up_name = new javax.swing.JLabel();
        jTextField_sign_up_name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField_sign_up_email = new javax.swing.JTextField();
        jLabel_sign_up_phone = new javax.swing.JLabel();
        jTextField_sign_up_phone = new javax.swing.JTextField();
        jLabel_sign_up_pass = new javax.swing.JLabel();
        jTextField_sign_up_pass = new javax.swing.JTextField();
        jLabel_sign_up = new javax.swing.JLabel();
        jButton_sign_up = new javax.swing.JButton();
        jTextField_sign_up_check = new javax.swing.JTextField();
        jLabel_ID = new javax.swing.JLabel();
        jLabel_password = new javax.swing.JLabel();
        jTextField_log_in_id = new javax.swing.JTextField();
        jTextField_log_in_password = new javax.swing.JTextField();
        jLabel_log_in = new javax.swing.JLabel();
        jButton_sign_up_here = new javax.swing.JButton();
        jButton_log_in = new javax.swing.JButton();
        jTextField_log_in_check = new javax.swing.JTextField();

        jLabel_sign_up_name.setText("Name");

        jLabel1.setText("Email");

        jLabel_sign_up_phone.setText("Phone number");

        jLabel_sign_up_pass.setText("Password");

        jLabel_sign_up.setText("SIGN UP");

        jButton_sign_up.setText("Sign up");
        jButton_sign_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_sign_upActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_sign_up_phone)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_sign_up_name, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_sign_up_pass, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField_sign_up_email)
                    .addComponent(jTextField_sign_up_name, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_sign_up_phone)
                    .addComponent(jTextField_sign_up_pass))
                .addGap(81, 81, 81))
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jLabel_sign_up))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jButton_sign_up))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jTextField_sign_up_check, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel_sign_up)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_sign_up_name)
                    .addComponent(jTextField_sign_up_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_sign_up_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_sign_up_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_sign_up_phone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_sign_up_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_sign_up_pass))
                .addGap(18, 18, 18)
                .addComponent(jButton_sign_up)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jTextField_sign_up_check, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("POKE'MON game");

        jLabel_ID.setText("ID");

        jLabel_password.setText("Password");

        jLabel_log_in.setText("LOG IN");

        jButton_sign_up_here.setText("Or sign up here");
        jButton_sign_up_here.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_sign_up_hereActionPerformed(evt);
            }
        });

        jButton_log_in.setText("OK");
        jButton_log_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_log_inActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel_log_in))
                    .addComponent(jButton_sign_up_here, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_password)
                            .addComponent(jLabel_ID))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_log_in)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField_log_in_password, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                .addComponent(jTextField_log_in_id)))))
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jTextField_log_in_check, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_log_in)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_ID)
                    .addComponent(jTextField_log_in_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_log_in_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_password))
                .addGap(12, 12, 12)
                .addComponent(jButton_log_in)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_log_in_check, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jButton_sign_up_here)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_sign_up_hereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_sign_up_hereActionPerformed
        // TODO add your handling code here:
        jFrame1.setSize(600, 300);
        jFrame1.setVisible(true);
    }//GEN-LAST:event_jButton_sign_up_hereActionPerformed

    private void jButton_sign_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_sign_upActionPerformed
        // TODO add your handling code here:
        Database db = new Database();
        db.CheckConn("kn", "1");
        String name = jTextField_sign_up_name.getText();
        String email = jTextField_sign_up_email.getText();
        String phone_nr = jTextField_sign_up_phone.getText();
        String pass = jTextField_sign_up_pass.getText();
        System.out.println(name + "\n " + email + "\n "+ phone_nr + "\n "+ pass);
        
        if ((int)sign_up_prod.ProcessEmail(email) == -2) {
            jTextField_sign_up_check.setText("Invalid email address, try again");
            return;
        }
        if (sign_up_prod.ProcessPhNumber(phone_nr) == -1) {
            jTextField_sign_up_check.setText("Ivalid phone number");
            return;
        }
        jTextField_sign_up_check.setText("Sign up successfully");
        db.SignUp(name, email, phone_nr, pass);
    }//GEN-LAST:event_jButton_sign_upActionPerformed

    private void jButton_log_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_log_inActionPerformed
        // TODO add your handling code here:
        Main main;
        Database db = new Database();
        db.CheckConn("kn", "1");
        int id = Integer.parseInt(jTextField_log_in_id.getText());
        String pass = jTextField_log_in_password.getText();
        db.LogIn(id, pass, user);
        if (user.getUser_name() == null) {
            jTextField_log_in_check.setText("ID or password not corrected, try again");
            return;
        }
        jTextField_log_in_check.setText("Welcome " + user.getUser_name());
        new Main();
    }//GEN-LAST:event_jButton_log_inActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_log_in;
    private javax.swing.JButton jButton_sign_up;
    private javax.swing.JButton jButton_sign_up_here;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_ID;
    private javax.swing.JLabel jLabel_log_in;
    private javax.swing.JLabel jLabel_password;
    private javax.swing.JLabel jLabel_sign_up;
    private javax.swing.JLabel jLabel_sign_up_name;
    private javax.swing.JLabel jLabel_sign_up_pass;
    private javax.swing.JLabel jLabel_sign_up_phone;
    private javax.swing.JTextField jTextField_log_in_check;
    private javax.swing.JTextField jTextField_log_in_id;
    private javax.swing.JTextField jTextField_log_in_password;
    private javax.swing.JTextField jTextField_sign_up_check;
    private javax.swing.JTextField jTextField_sign_up_email;
    private javax.swing.JTextField jTextField_sign_up_name;
    private javax.swing.JTextField jTextField_sign_up_pass;
    private javax.swing.JTextField jTextField_sign_up_phone;
    // End of variables declaration//GEN-END:variables
}
